#!/bin/sh
### BEGIN INIT INFO
# Provides:          cleantemporalthings
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Clean temporal things from the system
# Description:       It clean things like temporal dirs in /tmp
#
### END INIT INFO
# Policy Info:  http://wiki.debian.org/LSBInitScripts
# also check /etc/init.d/skeleton

# Author: Thanatermesis


# Defaults
PIDDIR=/var/run/cleantemporalthings
cleantemporalthingsPID=$PIDDIR/cleantemporalthings.pid
DESC="Clean temporal things from the system"
SCRIPTNAME=/etc/init.d/cleantemporalthings


# Reads config file (will override defaults above)
[ -r /etc/default/cleantemporalthings ] && . /etc/default/cleantemporalthings

. /lib/lsb/init-functions


do_start(){
    log_daemon_msg "Starting $(basename cleantemporalthings)"

    # Make sure we have our PIDDIR, even if it's on a tmpfs
    install -o root -g root -m 755 -d $PIDDIR

    log_progress_msg "daemonizing"

    #if ! start-stop-daemon --start --quiet --background --oknodo --exec /usr/sbin/cleantemporalthingsd -- -D
    if ! start-stop-daemon --start --quiet --background --make-pidfile --pidfile $cleantemporalthingsPID --oknodo --exec /usr/sbin/cleantemporalthingsd -- -D
    then
        log_end_msg 1
        exit 1
    fi


    #log_progress_msg "step 1 completed"
    true
    log_end_msg 0
}

do_stop(){
    log_daemon_msg "Stopping cleantemporalthings"
    #log_progress_msg "almost"

    start-stop-daemon --stop --quiet --pidfile $cleantemporalthingsPID
    # Wait a little and remove stale PID file
    if [ -f $cleantemporalthingsPID ] && ! ps h $(cat $cleantemporalthingsPID) > /dev/null
    then
        # Stale PID file (cleantemporalthings was succesfully stopped),
        # remove it (should be removed by cleantemporalthings itself IMHO.)
        rm -f $cleantemporalthingsPID
    fi


    log_end_msg 0
}

case "$1" in
    "")
        echo "Error: cleantemporalthings should be called with the 'start' argument." >&2
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|reload|force-reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: cleantemporalthings [start|stop]" >&2
        exit 3
        ;;
esac


