#!/bin/bash
### BEGIN INIT INFO
# Provides:          fixdevshm
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Fix /dev/shm permissions permanently
# Description:       Daemon to watch and maintain a compatible system
#
### END INIT INFO
# Policy Info:  http://wiki.debian.org/LSBInitScripts
# also check /etc/init.d/skeleton

# Author: Thanatermesis


# Defaults
PIDDIR=/var/run/fixdevshm
fixdevshmPID=$PIDDIR/fixdevshm.pid
DESC="Fix /dev/shm permissions permanently"
SCRIPTNAME=/etc/init.d/fixdevshm


# Reads config file (will override defaults above)
[ -r /etc/default/fixdevshm ] && . /etc/default/fixdevshm

. /lib/lsb/init-functions


do_start(){
    log_daemon_msg "Starting $(basename fixdevshm)"

    # Make sure we have our PIDDIR, even if it's on a tmpfs
    install -o root -g root -m 755 -d $$PIDDIR

    #log_progress_msg "daemonizing"

    if ! start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/fixdevshmd -- -D
    then
	log_end_msg 1
	exit 1
    fi


    log_progress_msg "step 1 completed"
    true
    log_end_msg 0
}

do_stop(){
    log_daemon_msg "Stopping fixdevshm"
    #log_progress_msg "almost"

    start-stop-daemon --stop --quiet --pidfile $fixdevshmPID
    # Wait a little and remove stale PID file
    sleep 1
    if [ -f $fixdevshmPID ] && ! ps h $(cat $fixdevshmPID) > /dev/null
    then
        # Stale PID file (fixdevshm was succesfully stopped),
        # remove it (should be removed by fixdevshm itself IMHO.)
	rm -f $fixdevshmPID
    fi


    log_end_msg 0
}

case "$1" in
    "")
        echo "Error: fixdevshm should be called with the 'start' argument." >&2
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|reload|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: fixdevshm [start|stop]" >&2
        exit 3
        ;;
esac


