#!/bin/sh
# note: argument -D is ignored, we do the background from another side

clean_tmp(){
    # only clean the known-ones:
    rmdir /tmp/xdg-* 2>/dev/null 1>&2

    # clean old efreet files (keep the last 8 ones)
    cd /tmp
    ls -1tr efreetd_* | head -n "-8" | xargs rm -f

    # always return ok
    return 0
}

main(){
    while true
    do
        clean_tmp
        sleep 7200 # 2 hours
    done
}

#
#  MAIN
#
main "$@"

# vim: set foldmethod=marker :

