#!/bin/sh
# note: argument -D is ignored, we do the background from another side

clean_tmp(){
    # only clean the known-ones:
    rmdir /tmp/xdg-* 2>/dev/null 1>&2

    # always return ok
    return 0
}

main(){
    # pre {{{

    # }}}

    while true
    do
        clean_tmp
        sleep 7200 # 2 hours
    done
}

#
#  MAIN
#
main "$@"

# vim: set foldmethod=marker :

