#!/bin/bash
# note: argument -D is ignored, we do the background from another side
SOURCE="$0"
source /usr/lib/elive-tools/functions
EL_REPORTS="1"
#el_make_environment
#. gettext.sh
#TEXTDOMAIN=""
#export TEXTDOMAIN



export LC_NUMERIC=C
export devshm="/dev/shm"

verify_and_fix_shm(){
    result="$( ls -ld "$(readlink -f "${devshm}" )" | awk '{print $1}' )"

    #note: asterisk * not works in /bin/sh
    #if [ "$result" != *rwxrwxrwt ] ; then
    if [ "$(readlink -f "$devshm" )" = "/run/shm" ] ; then
        if [ "$result" != drwxrwxrwt ] ; then
            logger "$(basename $0) - fixing permissions in ${devshm}, needs to be in 1777 and was '$result'"
            #echo "$(basename $0) - fixing permissions in ${devshm}, needs to be in 1777"
            chmod 1777 "$(readlink -f "${devshm}" )"
        fi
    else
        chmod 1777 "$(readlink -f "${devshm}" )"
    fi

    # nothing wrong by fixing it all the times no matter what
    #chmod 1777 "$(readlink -f "${devshm}" )"

    # always return true
    unset result
    return 0
}
#===  FUNCTION  ================================================================
#          NAME:  kill_processes_zombie
#   DESCRIPTION:  search and kill for zombie proceses
#    PARAMETERS:  -
#       RETURNS:  -
#===============================================================================
kill_processes_zombie(){
    # pre {{{
    local z_ppid z_pid z_state no_more_zombies z_ppid_comm

    no_more_zombies=0

    # }}}

    # get a list of zombie candidates (and only candidates, see grep -E)
    until ((no_more_zombies))
    do
        while read -ru 3 z_state z_pid z_ppid z_comm
        do
            if [[ -z "$z_ppid" ]] || [[ -z "$z_pid" ]] ; then
                unset z_pid z_ppid
                continue
            fi
            # get the parents process name
            z_ppid_comm="$(ps axo pid,comm | awk -v pid="$z_ppid" '{if($1 == pid)  { $1="" ; print $0 }}' | sed 's| $||g' )"
            read -r z_ppid_comm <<< "$z_ppid_comm"


            # ignore specific cases
            # ignore unison processes:
            #if [[ "$z_comm" = "timeout "* ]] ; then
            #if [[ "${z_ppid_comm}" = "unison" ]] ; then
            #continue
            #fi
            #fi
            # ignore chromium processes:
            #if [[ "$z_comm" = "chromium "* ]] ; then
            #if [[ "${z_ppid_comm}" = "chromium" ]] ; then
            #continue
            #fi
            #fi

            echo "Trying to recover the zombie '$z_pid' which parent is '$z_ppid' - (${z_comm})" 1>&2
            logger "$(basename $0) - Trying to recover the zombie '$z_pid' which parent is '$z_ppid' - (${z_comm})"

            if kill -s SIGCHLD "$z_ppid" ; then
                logger "$(basename $0) - $z_ppid killed"
            fi

            sleep 3
            if ps axo stat,pid,ppid | grep -q "^Z.*${z_pid}.*${z_ppid}" ; then
                logger "$(basename $0) - No luck, Killing parent of the zombie '$z_pid' which is '$z_ppid' - (${z_ppid_comm})" 1>&2

                if kill -9 "$z_ppid" ; then
                    logger "$(basename $0) - $z_ppid killed"
                fi
            fi
            sleep 3

            if kill -0 "$z_ppid" ; then
                el_warning "still having not-killed zombie processes? $(ps axo  stat,pid,ppid,comm | grep "^Z" )"
            fi

            unset z_pid z_ppid z_state z_comm

            # candidates for zombies: are you a winner ?
        done 3<<< "$( ps axo stat,pid,ppid,comm | grep -E "(plugin-conta|gvfsd-metada|tumblerd|enlightenment|ecomorph)" | grep "^Z" )"

        # they are all killed ? good job rude boy...
        if ! ps axo stat,pid,ppid | grep -E "(plugin-conta|gvfsd-metada|tumblerd|enlightenment|ecomorph)" | grep -q "^Z" ; then
            no_more_zombies=1
        fi
    done
}
#===  FUNCTION  ================================================================
#          NAME:  kill_process
#   DESCRIPTION:  kills a process
#    PARAMETERS:  $1 = pid, $2 (opt) = state, $3 (opt) = command/name , $4 (opt) = message
#       RETURNS:  -
#===============================================================================
kill_process(){
    # pre {{{
    local pid cmd state message

    pid="$1"
    state="$2"
    cmd="$3"
    message="$4"

    # get full name of command
    cmd="$( ps --no-headers -p $pid -o comm )"

    # }}}
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null ; then
        # zombies around, kill them
        if [[ "$state" = *Z* ]] ; then
            kill_processes_zombie
        fi

        if [[ -n "$message" ]] ; then
            echo -e "$message" 1>&2
            logger "$(basename $0) - $message"
        else
            if [[ -n "$cmd" ]] ; then
                echo "killing $cmd at ${pid}, cpu is at ${cpu_usage} since ${time_minutes} minutes" 1>&2
                logger "$(basename $0) - killing $cmd at ${pid}, cpu is at ${cpu_usage} since ${time_minutes} minutes"
            fi
        fi

        # always kill E with a SIGSEGV in order  to recover it
        # TODO: sometimes we have duplicated/zombified E processes that should be killed -9
        if [[ "$cmd" = *enlightenment* ]] ; then
            if kill -s SIGSEGV "$pid" 2>/dev/null 1>/dev/null ; then
                logger "$(basename $0) - $pid given a segfault to recover"
            fi
            sleep 1
            # nothing more here, we don't want to kill it more than a SEGV
            return 0
        fi

        if kill -0 "$pid" 2>/dev/null ; then
            if kill "$pid" 2>/dev/null 1>/dev/null ; then
                logger "$(basename $0) - $pid killed"
            fi
            sleep 1
        fi

        if kill -0 "$pid" 2>/dev/null ; then
            if kill -9 "$pid" 2>/dev/null 1>/dev/null ; then
                logger "$(basename $0) - $pid killed with -9"
            fi
            sleep 1
        fi

        if kill -0 "$pid" 2>/dev/null ; then
            el_warning "unable to kill process ${pid}, state ${state}, command ${cmd}, message ${message}"
        fi
    fi
}


main(){
    # pre {{{
    #local sleeptime pid user priority nice memvirt memresident memshared status cpu_usage mem_usage_percent cmd arg

    arg="$1"

    # }}}
    # sleep times: 120 = 2 minutes, 300 = 5 minutes
    sleeptime=300

    if [[ "$arg" = "onetime" ]] ; then
        is_onetime=1
    fi
    # watch and fix
    while true
    do
        # scan for annoying processes (sorted by cpu usage)
        LC_ALL=C COLUMNS=200 top -c -b -n 1 | head -n 200 | tail -n +8 | while read -r pid user priority nice memvirt memresident memshared status cpu_usage mem_usage_percent time_minutes cmd
        do
            # remove arguments included in command
            cmd="$( echo "$cmd" | awk '{print $1}' )"

            cpu_usage="${cpu_usage%.*}"
            mem_usage_percent="${mem_usage_percent%.*}"

            memvirt="${memvirt//G/000000}"
            memvirt="${memvirt//g/000000}"
            memvirt="${memvirt//M/000}"
            memvirt="${memvirt//m/000}"

            # break the loop from here, we don't need to check more than this
            if [[ "$cpu_usage" -lt 10 ]] ; then
                break
            fi

            time_minutes="${time_minutes%.*}"
            time_minutes="$(( $(( $(( ${time_minutes%%:*} * 60 )) + ${time_minutes##*:} )) / 60 ))"

            #
            # rules
            #

            #echo -e "D: checking command: $command with minutes: $time_minutes" 1>&2

            case "$cmd" in
                "gvfsd-metadata")
                    # gvfsd-daemon sometimes blocks sucking cpu cycles
                    if [[ "${time_minutes}" -ge 3 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        logger "$(basename $0) - annoying process detected (${cmd}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
                        kill_process "$pid" "${status}" "$cmd"
                    fi

                    ;;
                tumblerd)
                    # tumblerd sucking around
                    if [[ "${time_minutes}" -ge 10 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        logger "$(basename $0) - annoying process detected (${cmd}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
                        kill_process "$pid" "${status}" "$cmd"
                    fi

                    ;;
                mpg123*)
                    # mpg123 sometimes got stucked eating cpu
                    if [[ "${time_minutes}" -ge 15 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        logger "$(basename $0) - annoying process detected (${cmd}), minutes: ${time_minutes}, cpu usage: ${cpu_usage}, at pid: ${pid} "
                        kill_process "$pid" "${status}" "$cmd"
                    fi

                    ;;
                vlc|mplayer|gmplayer)
                    if [[ "${time_minutes}" -ge 180 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        # more than 3 hours with a video player consuming cpu == player stuck
                        kill_process "$pid" "${status}" "$cmd"
                    fi

                    ;;
                "enlightenment_fm")
                    # cpu sucking
                    if [[ "${time_minutes}" -ge 20 ]] && [[ "${cpu_usage}" -gt 80 ]] ; then
                        # note: eating cpu' FM's seems like to be in the R status
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    # huge mem usage
                    if [[ "${time_minutes}" -ge 30 ]] && [[ "${memvirt}" -gt 700000 ]] ; then
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    ;;
                enlightenment)
                    # cpu sucking
                    if [[ "${time_minutes}" -ge 30 ]] && [[ "${cpu_usage}" -gt 80 ]] ; then
                        el_warning "enlightenment is consuming high cpu for more than 30 min, pidofs: $(pidof enlightenment), ps: $(ps aux | grep "enlightenment" | grep -vE '(grep|enlightenment_s)' | tr '\n' ';' ), top: $( COLUMNS=200 top -c -b -n 1 | head -n 200 | tail -n +8 | grep "enlightenment" | grep -vE '(grep|enlightenment_s)' | tr '\n' ';' )"
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    # huge mem usage
                    if [[ "${time_minutes}" -ge 30 ]] && [[ "${memvirt}" -gt 1200000 ]] ; then
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    ;;
                ecomorph)
                    # huge mem usage
                    if [[ "${time_minutes}" -ge 30 ]] && [[ "${memvirt}" -gt 400000 ]] ; then
                        # it should use 50 mb on a small screen computer
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    ;;
                # whitelisted ones:  yeah, we know that they sucks, and we love them on this way :/
                "songbird-bin"|chromium|iceweasel*|*firefox*|Xorg|opera|VirtualBox|AppRun|pcsxr*)
                        # songbird:  its a simply greedy eater of resoureces
                        # chromium:  when we play videos cpu becomes high, and we could have it running since long time
                        # Xorg: sometimes is overloaded, its normal
                        true
                    ;;
                "rage_thumb")
                    # sometimes block
                    if [[ "${time_minutes}" -ge 30 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    ;;
                vlc)
                    # vlc like from /usr/lib/i386-linux-gnu/emotion/generic_players/v-1.13/vlc
                    # it should never run for more than 3 hours (long long movies?)
                    if [[ "${time_minutes}" -ge 180 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        kill_process "$pid" "${status}" "$cmd"
                    fi
                    ;;

                *)
                    if [[ "${time_minutes}" -gt 200 ]] && [[ "${cpu_usage}" -gt 60 ]] ; then
                        # note: keep this list updated so that we can always know if there's specific processes that should be included
                        if ! echo "$cmd" | grep -qsiE "^(chrome|google|Web Content|dropbox|FlatCAM.exe|mencoder|ffmpeg|lame|C:\\Program)$" ; then
                            # get full name of command
                            cmd="$( ps --no-headers -p $pid -o comm )"

                            el_warning "Annoying process detected '${cmd}' sucking cpu for '${time_minutes}' min, cpu usage '${cpu_usage}', pid '$pid' (ignored)"
                        fi
                    fi
                    ;;

            esac
        done


        # always kill long tumblerd's
        if killall --older-than 1h tumblerd 2>/dev/null ; then
            logger "$(basename $0) - stalled process detected (tumblerd), for more than 1 hour, killing it..."
            #el_warning "stalled process detected (tumblerd) for more than 1 hour, killing it..."
            killall -9 tumblerd
        fi

        # zombies
        kill_processes_zombie

        # clean some tmp things from E17 {{{
        # only clean the known-ones:
        rmdir /tmp/xdg-* 2>/dev/null 1>&2

        # clean old efreet files (keep the last 12 ones)
        if ls -1tr efreetd_* 1>/dev/null 2>&1 ; then
            ls -1tr efreetd_* | head -n "-12" | xargs rm -f
        fi

        # }}}
        # fix /dev/shm  {{{
        # ORIGINAL code from the old daemon, which run in a loop waiting for changes:
        # first fix
        #chmod 1777 "$( readlink -f "${devshm}" )"

        ## watch and fix
        #while true
        #do
            #while inotifywait -q -e modify -e attrib -e move -e create -e delete -e unmount "${devshm}" 1>/dev/null
                ##while inotifywait -e attrib -e move "${devshm}" # this one seems to not catch correctly all the times
            #do
                ## wait a few seconds in order to not overload the system with this daemon, seems like there's something that doesn't finish to change it
                ## this pause must be set before to change permissions, in order to directly listed again after that
                ##sleep 5

                ##echo "fixing ${devshm} permissions"
                ##echo -e "$(ls -l /dev | grep shm )" 1>&2
                ##echo -e "$(ls -l /run | grep shm | grep -v fixdev )" 1>&2

                ##logger "$(basename $0) - fixing permissions in ${devshm} | auto"
                ##chmod 1777 "${devshm}"

                ## a little pause so that we dont enter in infinite loops
                #sleep 4

                #verify_and_fix_shm

            #done
        #done

        # new code, just fix from time to time:
        verify_and_fix_shm

        # }}}

        # we only want to run it one time
        if ((is_onetime)) ; then
            exit
        fi

        # pause until the next loop
        sleep "$sleeptime"

        # clean vars
        unset pid user priority nice memvirt memresident memshared status cpu_usage mem_usage_percent time_minutes cmd
    done

}

#
#  MAIN
#
main "$@"

# vim: set foldmethod=marker :

