#!/bin/sh
# note: argument -D is ignored, we do the background from another side

# first fix
chmod 1777 /dev/shm

# watch and fix
while inotifywait -e modify -e attrib /dev/shm
do
    echo "fixing /dev/shm permissions"
    #logger "$(basename $0) - fixing permissions in /dev/shm"
    chmod 1777 /dev/shm
    # wait a few seconds in order to not overload the system with this daemon, seems like there's something that doesn't finish to change it
    sleep 10
done

